# version: "3.9"

services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/workspace
    tty: true
    gpus: all

  jupyter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - /mnt/c/dev/repos/oodkit:/workspace/repos/oodkit
      - /home/joeegan17/datasets:/datasets
    working_dir: /workspace/repos/oodkit
    gpus: all
    shm_size: "20gb"
    ports:
      - "8888:8888"
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --ServerApp.token=''
      --ServerApp.password=''
