# version: "3.9"

services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/workspace
    tty: true

  jupyter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8888:8888"
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --ServerApp.token=''
      --ServerApp.password=''
